Chapter9
nazihaltajar/TableViewProject pull request #1
Opened 2019-03-15 12:36 UTC by nazihaltajar

2019-03-15 12:39 UTC, alexbartisro requested changes
Please address remarks first

2019-03-15 12:39 UTC, trusk89 commented on Chapter9/Chapter9/RestaurantTableViewCell.swift
> +    override func awakeFromNib() {
It's nice to have newlines between code blocks

2019-03-15 12:39 UTC, trusk89 commented on Chapter9/Chapter9/RestaurantTableViewCell.swift
> +    override func awakeFromNib() {
This doesn't do anything, it's not needed

2019-03-15 12:39 UTC, trusk89 commented on Chapter9/Chapter9/RestaurantTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
Same

2019-03-15 12:39 UTC, trusk89 commented on Chapter9/Chapter9/RestaurantTableViewController.swift
> +    override func viewDidLoad() {
This doesn't do anything, it's not needed

2019-03-15 12:39 UTC, trusk89 commented on Chapter9/Chapter9/RestaurantTableViewController.swift
> +    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
Missing new line between code blocks

2019-03-15 12:39 UTC, trusk89 commented on Chapter9/Chapter9/RestaurantTableViewController.swift
> +
Extra new line

2019-03-15 12:40 UTC, alexbartisro requested changes

2019-03-15 12:40 UTC, trusk89 commented on Chapter9/Chapter9/RestaurantTableViewCell.swift
> +    @IBOutlet var nameLabel: UILabel!
It's good practice to make outlets private, in order not to be accessed directly

2019-03-15 13:21 UTC, alexbartisro approved these changes

2019-03-18 08:08 UTC, adinas23 commented on Chapter9/Chapter9/RestaurantTableViewController.swift
> +        let cellIdentifier = "datacell"
Rename it to ```dataCellIdentifier```

2019-03-18 10:28 UTC, merged